### ISSUE TITLE
Authorized Buyers UI Link - Bad Gateway

### ISSUE THREAD

**Issue by SockPastaRock** [googleads/authorized-buyers-rtb-api-samples#10]
In the documentation for the python library (likely true for other language documentation too) the link to the authorized buyers UI does not work.

In other support pages from google (found here: https://support.google.com/authorizedbuyers/answer/177141?hl=en), they instruct users to login to their authorized buyers account at https://realtimebidding.google.com/authorizedbuyers/Main.html but this link also fails to resolve.

Does this service no longer exist? I cannot find any documentation which appears to be up to date for how I can create and login to an authorized buyers account.

**Comment by msaniscalchi** [comment]
Hello, thanks for the report. I've confirmed that the link _does_ appear to work, although it doesn't respond in what I would consider an ideal way when accessed by a Google account that has no associated Authorized Buyers account–it will just result in a blank white screen. If you attempt to access it while logged out, you will be presented a login screen, and if you are logged in it will show the associated Authorized Buyers account details.

It might be better if this responded in a way that was more clear about the Google account used not having access to an AB account. I'll forward this feedback along to the engineering team. Otherwise, this seems to be working as intended.
